### ISSUE TITLE
Integrate more tools in CI

### ISSUE THREAD

**Issue by ROMemories** [future-proof-iot/RIOT-rs#108]
List of tools/functionalities we may want to integrate now in CI:

- [x] Check intra-doc links by building the docs of `riot-rs-embassy` with `-D warnings` #113
- [x] Only trigger the mdbook workflow when the `book/` directory was changed #111
- [x] Integrate [`cargo-sort`](https://github.com/DevinR528/cargo-sort) in CI #116
- [x] Check `rustfmt` formatting #118
- [x] Check intra-doc links by building the docs of `riot-rs` with `-D warnings` #132
- [x] Run crate tests for major crates #110  #139
- [ ] Make `clippy` check the whole workspace
- [ ] Run crate tests for the whole workspace

List of tools/functionalities we may want to integrate later in CI:

- [ ] [`cargo-semver-checks`](https://github.com/obi1kenobi/cargo-semver-checks) and/or [`cargo-public-api`](https://github.com/Enselic/cargo-public-api)
- [ ] [`miri`](https://github.com/rust-lang/miri)
- [ ] [`cargo-udeps`](https://lib.rs/crates/cargo-udeps)
- [x] [`cargo-deny`](https://github.com/embarkstudios/cargo-deny), [GitHub Action](https://github.com/EmbarkStudios/cargo-deny-action)
- [ ] Monitor binary size and static allocations of examples
