### ISSUE TITLE
[Tracking Issue] `riot-rs-threads`: add RISC-V support

### ISSUE THREAD

**Issue by elenaf9** [future-proof-iot/RIOT-rs#157]
As part of #7, RISC-V support should be added to the `riot_rs_threads` crate.

This mostly concerns the arch specific interrupt handling and context switching logic.

# TODO 

(more items might be added while I am working on this)

- [ ] Document existing scheduler/ multi-threading logic: #152 
- [x] Make `riot_rs_threads::arch::cortex_m::sched` arch-independent: #159 
- [x] #156
- [x] Implement `threads::arch::riscv` module: #182 
    - [x] Wire up the <s>exception</s> interrupt handler
    - [x] Implement context switch
    - [x] Implement some sort of WFI if no thread is ready (see https://github.com/future-proof-iot/RIOT-rs/pull/159#discussion_r1516992568)
    - [x] Implement `setup_stack` and `start_threading`

**Comment by kaspar030** [comment]
#182 closes this. Great work @elenaf9!
