### ISSUE TITLE
[Tracking Issue] Documentation Improvements

### ISSUE THREAD

**Issue by emmanuelsearch** [future-proof-iot/RIOT-rs#164]
Some pieces need to be improved/updated, while others are missing still. Let's track that here. (You spot more items? You think of a better substructure? You're welcome to modify/update or discuss it here!)

# TODO 

- [ ] Document RasPi Pico including Wifi use
- [ ] Add a new contributor guide #151 
- [ ] Update main README (see of instance #154)
- [ ] Add code of conduct #163
- [ ] Remove outdated documentation
- [ ] Initial mdbook drafting
    - [ ] Add Intro / Overview #153
    - [ ] Concept to structure the book
    - [ ] Automate book content updating (?)

**Comment by jkarinkl** [comment]
Good to have an overview on documentation to do's. Suggested additions:
 * [ ] Add a roadmap (see [background information](https://contribute.cncf.io/maintainers/community/contributor-growth-framework/open-source-roadmaps/))
 * [ ] Add a glossary, explaining basic words and processes (see [example](https://contribute.cncf.io/resources/glossary/))
 * [ ] Make a tutorial (not sure at what point in time this should be made. Is it too early?)
 

It would also be great to have a GOVERNANCE.md document in time. This helps clarify who has what role and how decisions are made. However, it is recommended to formalize this when a project is a bit further along, as it gradually becomes clear which form suits the project. 
- See background information from  [Open Source Guides](https://opensource.guide/leadership-and-governance/) and [Cloud Native](https://contribute.cncf.io/maintainers/governance/overview/). 
- An example from Grafana is found [here](https://github.com/grafana/grafana/blob/main/GOVERNANCE.md). 

It would be good to keep this in mind on what is desired on governance for the project, so that we can put it into a document easily in time.
