### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kaspar030** [future-proof-iot/RIOT-rs#242]
This is the Roadmap tracking issue.
Taken mostly unmodified from the initial [workplan](https://pad.riot-os.org/riot-rs-workplan?both#)

## Development tools

- [ ] Build system
  - [ ] evaluate & confirm or drop use of laze
- [ ] Testing Framework

## Core OS functionality

- [ ] Multicore support
  - [ ] Async executor on second core
  - [ ] Scheduler support for "regular" threads on both cores
- [ ] unify "console"
- [ ] Support defmt

## Embassy integration

- [x] Dispatch to correct embassy init()
- [x] Support per-board ~~drivers~~ initialization -> covered through riot-rs-boards & autostart tasks
- [x] Support application portability
  - [ ] 1. "portable" blinky
     This needs simple gpio or led abstraction (enumeration?)
 - [ ] 2. "portable" sensor reading
     This needs a way (in build system, code) to easily add sensor drivers.
 - [x] "portable" simple network application
 - [ ] make 2. / 3. networked
- [x] Get back linkme support

## Hardware Support

- [x] Extended Cortex-M support
  - [x] rpi-pico support
- [ ] RISCV support
  - [ ] Add any risc-v board
  - [ ] riot-rs-rt bringup
  - [ ] riot-rs-threads riscv task switching [PR](https://github.com/future-proof-iot/RIOT-rs/pull/182)
- [ ] "native" support
  
## RIOT-c support

(postponed)

## Basic (Layer<5) networking support

- [ ] Basic (Layer<5) networking support
- [ ] TCP/IP and UDP
- [ ] 802.15.4 / 6lowpan
- [ ] Bluetooth
- [ ] LoRa

## Extended (Layer>4) networking + security 

- [ ] MQTT
- [ ] [Low-power IPv6 IETF stack (CoAP/OSCORE/EDHOC)](./226)
- [ ] 802.15.4 link layer security
- [ ] TLS and DTLS
- [ ] Crypto library 

## Device Livecycle

- [ ] On-boarding
  - [ ] TOFU
  - [ ] Zero-Touch
- [ ] SUIT

## Extend embassy integration

- [ ] low-power
- [ ] Multiple timers
- [ ] ~~Board support trait~~ not using a trait

## Extend hardware support

- [ ] re-think riot-rs-boards
- [ ] nrf5340
- [ ] stm32

## CI

- [ ] set up CI testing on hardware

**Comment by chrysn** [comment]
Addendum for Device Lifecycle:

* On-boarding
  * [ ] Explicit / dedicated configuration.

    When networking itself requires onboarding that has neither TOFU nor Zero-Touch capabilities, it'd be convenient to have a cheap extra on-boarding channel. This may be USB Ethernet, WebUSB or Bluetooth, which can set up WiFi credentials. Using that interface should ideally be accessible to users unfamiliar with programming, eg. by having configuration options exposed as MTP files, or even a web application that provides different levels of interface to an attached device's configuration (eg. key-value manipulation or forms for described fields).

    (inspired by [a fedi thread](https://chaos.social/@chrysn/112803944916314295))
