### ISSUE TITLE
tracking: SMP Support 

### ISSUE THREAD

**Issue by elenaf9** [future-proof-iot/RIOT-rs#243]
# Summary

Add support for symmetric multiprocessing (SMP), i.e. platforms with multiple symmetric cores. 
An example for such a platform is the Raspberry RP2040, with Dual ARM Cortex-M0+ cores.

## Subtasks for basic a implementation 

A first implementation for the RP2040 is drafted in #241. There is quite a lot still missing there.
The below list includes some central tasks, but will grow while I am working on this.

- [x] ~#244~
- [x] Multicore support in the scheduler: #397 
  - [x] Schedule `n` highest-priority threads on the `n` cores
  - [x] Trigger scheduler of other cores
  - [x] Idle thread for each core
  - [x] Affinity Masks 
  - [x] Optimize scheduler invocations to reduce context switches and priority inversion
  - [x] Supported chips:
    - [x] RP2040 
    - [x] ESP32S3 
- [ ] Optimize locking primitives (spinlocks for shared resources, scheduler lock, ...)
  - Test different levels of locking (fine-grained vs one global lock)
  - Use independent internal critical section 

Additional features (to be discussed):
- [ ] Priority inheritance (for threads holding a shared resource). Started in #398. (_Is this orthogonal?_) 

## Benchmarks

The implementation should be tested with benchmarks to compare the performance with the single-core version.
Off the top of my head, some interesting metrics would be:
- Response time
- Makespan
- Priority inversions
- ...

_Edit: a set of benchmarks is currently implemented outside of this repo: [elenaf9/RIOT-rs-application](https://github.com/elenaf9/RIOT-rs-applications). Selected benchmarks will be moved in this repo eventually_).

**Comment by kaspar030** [comment]
I consider this done, #389 is orthogonal.
