### ISSUE TITLE
tracking: use of unstable features

### ISSUE THREAD

**Issue by kaspar030** [future-proof-iot/RIOT-rs#298]
We're aiming to build with stable Rust.

Currently, we're using these unstable features:

1. can't do without:
  - [ ] [`used_with_arg`](https://github.com/rust-lang/rust/issues/93798): this is used by linkme for its distributed slices

2. could do without:
- [ ] [`type_alias_impl_trait`](https://github.com/rust-lang/rust/issues/63063) => embassy uses this or pre-allocate futures memory
- [ ] `const_mut_refs`: used by ringbuffer
- [ ] `custom_test_frameworks`: will go when we have migrated to `defmt-test`
- [ ] `doc_auto_cfg`
- [ ] `error_in_core`
- [ ] `fn_traits`
- [ ] `inline_const`
- [ ] [naked_functions](https://github.com/rust-lang/rust/issues/90957): used by `riot-rs-threads`

**Comment by josephcsible** [comment]
>     * [ ]  [`negative_impls`](https://github.com/rust-lang/rust/issues/68318); used for `!Send` on `MutexGuard`

Could you get rid of that by adding something like `_not_send: PhantomData<*const ()>` to `MutexGuard` instead?

**Comment by kaspar030** [comment]
Where are `fn_traits` used?

```shell
❯ git grep fn_traits
ariel-os on  main took 24ms 
❯ 
```

**Comment by ROMemories** [comment]
> Where are `fn_traits` used?

I'm not sure, I searched for it in my fork as well (in case that was for the sensor abstraction), but couldn't find anything. I removed it from the list.

**Comment by kaspar030** [comment]
> This leaves only `used_with_arg`, and that we might manage by virtue of having good control of linker scripts ([#639](https://github.com/ariel-os/ariel-os/issues/639)?)

I'll give solving `used_with_arg` another shot.

**Comment by kaspar030** [comment]
`ariel-os-debug-log` is using `macro_metavar_expr`

**Comment by ROMemories** [comment]
Closing this, we've been able to build on stable since https://github.com/ariel-os/ariel-os/pull/951, and even with stable Cargo since #1811. The only remaining unstable features in the OS are `doc_cfg` (which is used only for documentation) and `asm_experimental_arch` on Xtensa (but the whole Xtensa toolchain is unstable and nightly). Such features can trivially be grepped for using `feature\(`.

The only other occurrence is in the `http-server` *application*, because `picoserve` needs `impl_trait_in_assoc_type`, but it's not part of the OS itself.
