### ISSUE TITLE
tracking: most wanted laze improvements

### ISSUE THREAD

**Issue by kaspar030** [future-proof-iot/RIOT-rs#416]
List of UX conveniences (and bugs) that we've identified:

- [ ] having both laze.yml and Cargo.toml for apps seems redundant, fold into one
- [ ] have laze deduce laze modules from Cargo features (solve https://github.com/future-proof-iot/RIOT-rs/issues/410#issuecomment-2348500579)
- [ ] improve errors
  - [ ] unused laze.yml
  - [ ] laze called from folder where there is no application defined
  - [ ] ...
- [ ] inconsistent tasks, e.g., "flash", "flash-rs", ...

**Comment by bergzand** [comment]
>     * [ ]  inconsistent tasks, e.g., "flash", "flash-rs", ...

  * [ ] `run` calls probe-rs, `flash` calls openocd
